version: 2
updates:
  - package-ecosystem: "npm"        # npm ecosystem for Node.js projects
    directory: "/"                   # Root directory where package.json is located
    schedule:
      interval: "weekly"             # Check for updates weekly
    commit-message:
      prefix: "fix"                  # Prefix for commit messages (e.g., "fix" or "chore")
    groups:
      all-updates:                   # Group name for all updates
        patterns:
          - "*"                      # Include all dependencies
        update-types:
          - "major"                  # Include major updates
          - "minor"                  # Include minor updates
          - "patch"                  # Include patch updates
          - "security"               # Include security updates
